### ISSUE TITLE
Error message is too invasive

### ISSUE THREAD

**Issue by dpgil** [avadavat/truth-fiddle#10]

**Comment by rniemo** [comment]
can we get a description & definition of done here?

**Comment by jbadlato** [comment]
With all the new syntax options, this issue has become even worse: https://www.truthfiddle.com?q=p%20%20q

**Comment by dpgil** [comment]
U added all the new syntax options 🤣🤣

**Comment by rniemo** [comment]
please dont change this, the error message being so long is part of my workflow.

**Comment by jbadlato** [comment]
Closed with 876896f9101ae417771268d11d69cded2aa7668e
