### ISSUE TITLE
Deploy the application

### ISSUE THREAD

**Issue by dpgil** [avadavat/truth-fiddle#13]
Is heroku the best option?

**Comment by jbadlato** [comment]
I think I can host this on the digital ocean droplet I’m using for markovrankings, I’ll look into. Digital Ocean would definitely be preferable

**Comment by dpgil** [comment]
Sounds good. Out of curiosity what advantages does digital ocean bring?

**Comment by jbadlato** [comment]
Biggest is no mandatory down time (heroku is 8hrs out of every 24 I think) and no start up time. Or if you pay for heroku, then price. 

Also have pretty much 100% control over everything with the Digital Ocean droplet. I assume this deployment will be very simplistic so I don’t expect it to be too much work

**Comment by jbadlato** [comment]
www.truthfiddle.com
