### ISSUE TITLE
Use of XOR results in output being 1/0 instead of true/false

### ISSUE THREAD

**Issue by jbadlato** [avadavat/truth-fiddle#21]
Reproduce by inputting: `p xor q`

p | q | Result
-- | -- | --
false | false | 0
false | true | 1
true | false | 1
true | true | 0

**Comment by jbadlato** [comment]
6043dfd3c7cd798b454a6bae3affe6fe73bba488 fixed this as far as the user is concerned, but it's probably worth taking a look at how the result value is generated...seems strange that it would return 1/0 when xor is involved but T/F otherwise.  Javascript takes care of this with its truthy/falsy checks anyway though

**Comment by dpgil** [comment]
I think the reason for this is that there is no logical xor operation, only a bitwise one. We would expect the same type of results if we used `&` for and instead of `&&`. Going to close this since your commit addressed the issue

**Comment by dpgil** [comment]
We could also compute xor as `p != q` instead of `p ^ q`, which would give us booleans instead of numbers.
