### ISSUE TITLE
SEO so our site is actually search-able

### ISSUE THREAD

**Issue by jbadlato** [avadavat/truth-fiddle#23]
I'm not 100%, but I'm pretty sure as it is right now, as far as google is concerned, our entire site is: 

```"You need to enable JavaScript to run this app."```

Not trying to go too deep here, but when you search "Truth Fiddle" or "truth table generator" it should come up.  

https://medium.com/@prestonwallace/3-ways-improve-react-seo-without-isomorphic-app-a6354595e400

**Comment by rniemo** [comment]
ill put in a word

**Comment by jbadlato** [comment]
Requested indexing from google, got the analytics started (66f055657a5b83005fa04475a4b8ab70b1690818), and added description to the header (e3dda1b5917df69692d6539d81752c5fd8e71465).  Google is definitely running the app correctly :grinning:
