### ISSUE TITLE
Not operator should take highest precedence

### ISSUE THREAD

**Issue by dpgil** [avadavat/truth-fiddle#25]
`not p and q` should be `(not p) and q` in terms of precedence. Our current logic evaluates it as `not (p and q)`.

**Comment by rniemo** [comment]
it's been two weeks since this was opened. Can you give an update? this is breaking my workflow.

**Comment by jbadlato** [comment]
@rniemo Sorry for the delay--it should be resolved now.  Let me know if you run into any other blockers.

**Comment by dpgil** [comment]
@jbadlato thanks for the quick turnaround!

**Comment by dpgil** [comment]
@rniemo feedback from our users is essential for us to make sure we're on the right track with the product. do u like the fix?

**Comment by rniemo** [comment]
@jbadlato @dpgil 

hey folks. i just want to start off by saying how proud i am.

a few months ago.. no, actually, late last year... no, not that. more than that. literally last **decade** you had a concerned user ask you to tackle a challenging problem. a problem by which the brightest minds of our generation had been stumped, fooled, betwixted, muddled, taken for a loop, taken for a spin, taken for a drive, taken around the block.... i think you get my point. excuse me for getting carried away, let me refocus.

the summary is this. you took this issue head on. you applied it directly to the forehead. you were headstrong. headstrong to take any problem on. what i'm trying to say is your skulls are jacked. and what came out of those jacked skulls is beauty. beauty for everyone involved. beauty for our users, beauty for the compiler (i believe your code created the first ever recorded tears of joy that a compiler has ever emitted), beauty for the metal that got to execute the output of the compiler, and, i cannot stress this enough, beauty in the value you've created for our shareholders.

thank you for setting an example for the world, Daniel and Joe. in times like these we need leadership, and you have provided in bounty. Though it is the fashion of the day to turn the ear when the cries of the user enter it, you turned towards the cries. You met pleading eyes with a gentle gaze, and spoke:

"Sorry for the delay--it should be resolved now. Let me know if you run into any other blockers."
