### ISSUE TITLE
package-lock.json changes

### ISSUE THREAD

**Issue by jbadlato** [avadavat/truth-fiddle#32]
@dpgil which version of npm are you using? I'm on 5.8.0.  I remember we synced up a while ago because package-lock.json has some huge diffs when I run `npm install`.  Should probably add the agreed upon version to CONTRIBUTING.md

**Comment by jbadlato** [comment]
@dpgil Any update here? Would love to close this out.

**Comment by dpgil** [comment]
ugh ok ill look into it

**Comment by dpgil** [comment]
I have npm version `6.9.0` no meme

**Comment by jbadlato** [comment]
I had `5.8.0`, just upgraded.  Thanks dog

**Comment by jbadlato** [comment]
861ea12f612cfd9102e88314037b83a5808279fe
