### ISSUE TITLE
help me figure out codeship lol

### ISSUE THREAD

**Issue by dpgil** [avadavat/truth-fiddle#46]
@jbadlato since u read github more frequently than ur text messages do u think u could help me figure out how I can get access to codeship

i'm pretty sure I had access before on my MICROSOFT email 🤦‍♂ I uhhh don't have access to that anymore

**Comment by dpgil** [comment]
@jbadlato @jbadlato

**Comment by jbadlato** [comment]
Ouch

**Comment by dpgil** [comment]
thx
